### ISSUE TITLE
Downloaded the wrong testcase

### ISSUE THREAD

**Issue by ZnPdCo** [conlacda/atcoder-companion#4]
In the problem https://atcoder.jp/contests/arc065/tasks/arc065_c, 
The correct download link for testcase is https://github.com/conlacda/atcoder-testcases/tree/arc065/arc065/E. However it download https://github.com/conlacda/atcoder-testcases/tree/arc065/arc065/C. 

I think it needs to identify the testcase link through the question title instead of the URL.

**Comment by conlacda** [comment]
@ZnPdCo 
Thank you. I will fix it and release it soon.
