### ISSUE TITLE
Messy PID and testcase: For competitions with same problems, it is difficult to identify the testcase URL

### ISSUE THREAD

**Issue by ZnPdCo** [conlacda/atcoder-companion#7]
https://atcoder.jp/contests/abc049/tasks/abc049_a, the testcase link should be arc065_a. But it difficulty to identify the testcase URL.

Maybe we can identify the testcase URL from the last problem in this contest and this problem's title?

**Comment by conlacda** [comment]
Thank you so much. Let me fix it.

**Comment by conlacda** [comment]
@ZnPdCo 
I made pull request #8 to fix this issue and #4 #5 as well. 
Please help me to check if the issues related to test cases remain or not.
Thank you for your time.

**Comment by ZnPdCo** [comment]
> @ZnPdCo I made pull request #8 to fix this issue and #4 #5 as well. Please help me to check if the issues related to test cases remain or not. Thank you for your time.

It work, thank you.
